include: package:pedantic/analysis_options.yaml

analyzer:
  exclude: [lib/**.g.dart]
  # TODO: Enable strong mode
  # strong-mode:
  #   implicit-casts: false
  #   implicit-dynamic: false
  errors:
    todo: ignore

dart_code_metrics:
  anti-patterns:
    - long-method:
        severity: error
    - long-parameter-list:
        severity: error
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-parameters: 4
    source-lines-of-code: 50
    number-of-methods: 10
  metrics-exclude:
    - test/**
  rules:
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-conditional-expressions
    - no-equal-then-else
    - no-magic-number:
        severity: style

linter:
  rules:
    # Error rules
    avoid_empty_else: true
    avoid_relative_lib_imports: true
    avoid_types_as_parameter_names: true
    empty_statements: true
    iterable_contains_unrelated_type: true
    throw_in_finally: true

    # Pub rules
    sort_pub_dependencies: false

    # Style rules
    annotate_overrides: true
    avoid_init_to_null: true
    avoid_null_checks_in_equality_operators: true
    avoid_renaming_method_parameters: true
    avoid_returning_null_for_void: true
    avoid_shadowing_type_parameters: true
    avoid_unnecessary_containers: true
    avoid_unused_constructor_parameters: true
    await_only_futures: true
    camel_case_extensions: true
    camel_case_types: true
    depend_on_referenced_packages: false
    empty_catches: true
    empty_constructor_bodies: true
    exhaustive_cases: true
    file_names: true
    implementation_imports: false
    join_return_with_assignment: true
    library_names: true
    library_prefixes: true
    lines_longer_than_80_chars: true
    non_constant_identifier_names: true
    no_leading_underscores_for_local_identifiers: true
    null_check_on_nullable_type_parameter: true
    null_closures: true
    prefer_collection_literals: true
    prefer_conditional_assignment: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_contains: true
    prefer_function_declarations_over_variables: true
    prefer_generic_function_type_aliases: true
    prefer_if_null_operators: true
    prefer_initializing_formals: true
    prefer_interpolation_to_compose_strings: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_is_not_operator: true
    prefer_null_aware_operators: true
    prefer_spread_collections: true
    prefer_typing_uninitialized_variables: true
    recursive_getters: true
    sort_child_properties_last: true
    unnecessary_brace_in_string_interps: true
    unnecessary_const: true
    unnecessary_new: true
    unnecessary_null_aware_assignments: true
    unnecessary_late: true
    unnecessary_overrides: true
    unnecessary_string_escapes: true
    unnecessary_string_interpolations: true
    unnecessary_this: true
    use_function_type_syntax_for_parameters: true
    use_rethrow_when_possible: true
